[package]
name = "quantum-bitcoin"
version = "0.1.0"
edition = "2021"

[dependencies]
pqcrypto-dilithium = { version = "0.5.0", features = ["serialization"] }
pqcrypto-traits = "0.3.5"
rand = "0.8.5"
secp256k1 = { version = "0.30.0", features = ["rand", "std", "hashes"] }
sha2 = "0.10.8"
